---

- name: Ensure generic application packages are installed
  apt:
    name:
      - firefox-esr
      - chromium
      - chromium-sandbox
      - thunderbird
      - evince
      - libreoffice
      - hyphen-en-gb
      - gimp
    state: present
