---

- name: Ensure desktop environment packages installed
  apt:
    name: 
      - lightdm
      - network-manager-gnome
      - gnome-themes-extra
    state: present

- name: Ensure LaTeX and dependendencies are installed
  apt:
    name: ['texlive-full']
    state: present

- import_tasks: scan-client.yml
- import_tasks: print-client.yml
- import_tasks: cron.yml
