---

- name: Ensure flexget packages installed
  apt:
    name:
      - python3
      - python3-setuptools
      - python3-dev
      - python3-pip
      - python3-sqlalchemy
      - virtualenv
    state: present

- name: Ensure that transmission rpc is a compatible version
  pip:
    name: transmission-rpc
    state: present
    version: 4.3.1
    virtualenv: "{{ flexget.venv_home }}"
    virtualenv_site_packages: true
  notify: restart flexget

- name: Ensure that flexget is installed via pip
  pip:
    name: flexget
    state: present
    virtualenv: "{{ flexget.venv_home }}"
    virtualenv_site_packages: true
  notify: restart flexget

- name: Ensure that flexget user exists
  user:
    name: "{{ flexget.user }}"
    state: present
    create_home: true
    system: true

- name: Ensure that defaults file is set
  template:
    src: flexget_template.j2
    dest: /etc/default/flexget
  notify: restart flexget

- name: Ensure that systemd is configured
  template:
    src: flexget-bookworm.service.j2
    dest: /usr/lib/systemd/system/flexget.service
  notify: restart flexget

- name: Ensure that service is enabled
  service:
    name: flexget
    enabled: yes
