---
- name: Ensure flexget packages installed
  apt: name={{ item }} state=installed
  with_items:
    - python2.7
    - python-pip

- name: Ensure that pip is updated
  pip: name=setuptools state=latest

# The "testrepository" package is needed for some reason
# https://ask.openstack.org/en/question/86725/got-an-error-during-installation-of-kilo-error-in-setup-command-error-parsing-optstackkeystonesetupcfg-importerror-no-module-named-testrepository/
- name: Ensure that testrepository is installed
  pip: name=testrepository state=present

- name: Ensure that flexget is installed
  pip: name=flexget state=latest
  notify: restart flexget

- name: Ensure that defaults file is set
  template: src=flexget_template.j2 dest=/etc/default/flexget
  notify: restart flexget

- name: Ensure that init script is set
  copy: src=flexget_init dest=/etc/init.d/flexget mode=0755
  notify: restart flexget

- name: Ensure that service is enabled
  service: name=flexget enabled=yes
