---

- name: Ensure flexget packages installed
  apt: name={{ item }} state=installed
  with_items:
    - python2.7
    - python-setuptools
    - python2.7-dev

- name: Ensure that apt pip is gone
  apt: name={{ item }} state=absent
  with_items:
    - python-pip

- name: Ensure pip is installed
  easy_install: name=pip state=latest

- name: Ensure that pip is updated
  pip: name=setuptools state=latest

- name: Ensure that functools32 is installed
  pip: name=functools32 state=latest

- name: Ensure that TransmissionRPC is installed
  pip: name=transmissionrpc state=latest
  notify: restart flexget

- name: Ensure that sqlalchemy is the latest
  pip: name=sqlalchemy state=latest
  notify: restart flexget

- name: Ensure that flexget is installed
  pip: name=flexget state=present version=2.3.0
  notify: restart flexget

- name: Ensure that defaults file is set
  template: src=flexget_template.j2 dest=/etc/default/flexget
  notify: restart flexget

- name: Ensure that init script is set
  copy: src=flexget_init dest=/etc/init.d/flexget mode=0755
  notify: restart flexget

- name: Ensure that service is enabled
  service: name=flexget enabled=yes
