---

- name: Ensure flexget packages installed
  apt:
    name: ['python3', 'python3-setuptools', 'python3-dev', 'python3-pip']
    state: present

- name: Ensure that pip is updated
  pip:
    name: setuptools
    state: latest
    executable: /usr/bin/pip3

#- name: Ensure that functools32 is installed
#  pip:
#    name: functools32
#    state: latest
#    executable: /usr/bin/pip3

- name: Ensure that TransmissionRPC is installed
  pip:
    name: transmissionrpc
    state: latest
    executable: /usr/bin/pip3
  notify: restart flexget

- name: Ensure that sqlalchemy is the latest
  pip:
    name: sqlalchemy
    state: latest
    executable: /usr/bin/pip3
  notify: restart flexget

- name: Ensure that flexget is installed
  pip:
    name: flexget
    state: present
    version: 2.10.107
    executable: /usr/bin/pip3
  notify: restart flexget

- name: Ensure that defaults file is set
  template:
    src: flexget_template.j2
    dest: /etc/default/flexget
  notify: restart flexget

- name: Ensure that init script is set
  copy:
    src: flexget_init
    dest: /etc/init.d/flexget
    mode: 0755
  notify: restart flexget

- name: Ensure that service is enabled
  service:
    name: flexget
    enabled: yes
