---

- name: Ensure clamav is installed
  apt: name={{ item }} state=present
  with_items:
    - clamav-freshclam
    - clamav

- name: Ensure daily scan is setup
  template: src=clamscan.j2 dest=/etc/cron.daily/clamscan mode=0755

