---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - core

- hosts: all
  roles:
    - dot-files

- hosts: print-servers
  become: yes
  become_method: sudo
  roles:
    - print-server

- hosts: scan-servers
  become: yes
  become_method: sudo
  roles:
    - scan-server

- hosts: media-servers
  become: yes
  become_method: sudo
  roles:
    - media-servers
    - samba
    - transmission
    - flexget
    - media-clamscan
    - tv-management
    - get-iplayer

- hosts: backup-servers
  become: yes
  become_method: sudo
  roles:
    - backup-host
    - { role: s3cmd }

- hosts: ups-hosts
  become: yes
  become_method: sudo
  roles:
    - apcupsd

- hosts: apt-cache-servers
  become: yes
  become_method: sudo
  roles:
    - apt-cacher-ng

- hosts: dns-servers
  become: yes
  become_method: sudo
  roles:
    - dns-server

- hosts: dhcp-servers
  become: yes
  become_method: sudo
  roles:
    - dhcp-server

- hosts: desktop
  become: yes
  become_method: sudo
  roles:
    - backup-client
    - media-client
    - demetria-dualscreen
    - desktop
    - software-development
