---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - core

- hosts: print-servers
  become: yes
  become_method: sudo
  roles:
    - print-server

- hosts: scan-servers
  become: yes
  become_method: sudo
  roles:
    - scan-server

- hosts: media-servers
  become: yes
  become_method: sudo
  roles:
    - { role: yamb00.samba }
    - transmission
    - flexget
    - clamav
    - media-clamscan
    - tv-management
    - get-iplayer

- hosts: backup-servers
  become: yes
  become_method: sudo
  roles:
    - backup-host
