---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - core

- hosts: all
  roles:
    - dot-files

- hosts: print_servers
  become: yes
  become_method: sudo
  roles:
    - print-server

- hosts: scan_servers
  become: yes
  become_method: sudo
  roles:
    - scan-server

- hosts: media_servers
  become: yes
  become_method: sudo
  roles:
    - media-servers
    - samba
    - transmission
    - flexget
    - media-clamscan
    - tv-management
    - get-iplayer

- hosts: backup_servers
  become: yes
  become_method: sudo
  roles:
    - backup-host
    - { role: s3cmd }

- hosts: ups_hosts
  become: yes
  become_method: sudo
  roles:
    - apcupsd

- hosts: apt_cache_servers
  become: yes
  become_method: sudo
  roles:
    - apt-cacher-ng

- hosts: dns_servers
  become: yes
  become_method: sudo
  roles:
    - dns-server

- hosts: desktop
  become: yes
  become_method: sudo
  roles:
    - backup-client
    - media-client
    - desktop
    - software-development
    - iptables
    - sainsburys-workstation
