---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - core

- hosts: print-servers
  become: yes
  become_method: sudo
  roles:
    - print-server

- hosts: scan-servers
  become: yes
  become_method: sudo
  roles:
    - scan-server

- hosts: samba-servers
  become: yes
  become_method: sudo
  roles:
    - { role: yamb00.samba }

- hosts: transmission-servers
  become: yes
  become_method: sudo
  roles:
    - transmission

