---

- name: Ensure desktop packages installed
  apt:
    name: ['chromium', 'chromium-sandbox', 'thunderbird', 'kmymoney', 'keepass2', 'mono-complete', 'xdotool', 'tumbler-plugins-extra', 'gramps', 'redshift', 'redshift-gtk', 'gir1.2-goocanvas-2.0', 'libgoocanvas-2.0-9', 'python3-networkx', 'python3-pygraphviz', 'python3-pydotplus', 'oxygen-icon-theme', 'evince']
    state: present

#- name: Ensure slack dependencies installed
#  apt: name={{ item }} state=installed
#  with_items:
#    - gconf2
#    - gvfs-bin
#    - apt-transport-https
#    - libappindicator1
#    - libcurl3

- name: Ensure LaTeX and dependendencies are installed
  apt:
    name: ['texlive-full']
    state: present

- include: scan-client.yml
- include: print-client.yml
- include: cron.yml
