---

- name: Ensure desktop environment packages installed
  apt:
    name: 
      - redshift
      - redshift-gtk
      - lightdm
      - network-manager-gnome
      - fonts-dejavu
      - tumbler-plugins-extra
      - gnome-keyring
      - gnome-themes-extra
    state: present

#- name: Ensure slack dependencies installed
#  apt: name={{ item }} state=installed
#  with_items:
#    - gconf2
#    - gvfs-bin
#    - apt-transport-https
#    - libappindicator1
#    - libcurl3

- name: Ensure LaTeX and dependendencies are installed
  apt:
    name: ['texlive-full']
    state: present

- include: generic-applications.yml
- include: scan-client.yml
- include: print-client.yml
- include: cron.yml
- include: family-history.yml
