---

- name: Ensure desktop environment packages installed
  apt:
    name: 
      - redshift
      - redshift-gtk
      - lightdm
      - network-manager-gnome
      - fonts-dejavu
      - tumbler-plugins-extra
      - gnome-keyring
      - gnome-themes-extra
    state: present

- name: Ensure LaTeX and dependendencies are installed
  apt:
    name: ['texlive-full']
    state: present

- import_tasks: generic-applications.yml
- import_tasks: scan-client.yml
- import_tasks: print-client.yml
- import_tasks: cron.yml
- import_tasks: family-history.yml
