---

- name: Ensure desktop packages installed
  apt: name={{ item }} state=installed
  with_items:
    - chromium
    - thunderbird
    - kmymoney
    - keepass2
    - xdotool
    - tumbler-plugins-extra

- name: Ensure slack dependencies installed
  apt: name={{ item }} state=installed
  with_items:
    - gconf2
    - gvfs-bin
    - apt-transport-https
    - libappindicator1
    - libcurl3

- name: Ensure LaTeX and dependendencies are installed
  apt: name={{ item }} state=installed
  with_items:
    - texlive-full

- include: scan-client.yml
- include: print-client.yml
