---

- name: Ensure desktop packages installed
  apt:
    name: ['chromium', 'chromium-sandbox', 'thunderbird', 'kmymoney', 'keepass2', 'xdotool', 'tumbler-plugins-extra', 'gramps']
    state: present

#- name: Ensure slack dependencies installed
#  apt: name={{ item }} state=installed
#  with_items:
#    - gconf2
#    - gvfs-bin
#    - apt-transport-https
#    - libappindicator1
#    - libcurl3

- name: Ensure LaTeX and dependendencies are installed
  apt:
    name: ['texlive-full']
    state: present

- include: scan-client.yml
- include: print-client.yml
- include: cron.yml
