---

- name: Ensure dns software is installed
  apt: name=bind9
       state=present

- name: Ensure local options are configured
  template:
    src=named.conf.options.j2
    dest=/etc/bind/named.conf.options
    owner=root
    group=bind
    mode=0644
    validate="/usr/sbin/named-checkconf %s"
  notify: restart dns
