---

- name: Ensure that saned is installed
  apt: name={{ item }} state=present
  with_items:
    - sane-utils
    - libsane
    - libsane-extras
  notify:
    - restart sane

- name: Ensure fix for epson scanner is applied
  lineinfile: dest=/etc/sane.d/epson2.conf regexp=^usb line="usb 0x04b8 0x0864"
  notify:
    - restart sane

- name: Ensure that saned and scanner users are in the scanner group
  user: name={{ item }} append=yes groups=scanner,lp
  with_items:
    "{{ scanner_users + ['saned'] }}"
  notify:
    - restart sane

- name: Ensure that saned is enabled
  lineinfile: dest=/etc/default/saned regexp=^RUN= line=RUN=yes
  notify:
    - restart sane

- name: Ensure that saned config is correct
  template: dest=/etc/sane.d/saned.conf backup=yes src=saned.conf.j2
  notify:
    - restart sane

- name: Ensure that saned service is enabled
  service: name=saned.socket enabled=yes
  notify:
    - restart sane


