---
galaxy_info:
  role_name: zoom
  author: Derek Kaye
  description: Sets up software needed for processing marked electoral registers
  license: GPLv3
  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - bullseye

dependencies: []
