---

- name: Ensure apt is properly configured
  copy:
    src=apt-cacher
    dest=/etc/apt/apt.conf.d/10aptcacher
    owner=root
    group=root
    mode=0644

- name: Ensure apt cache up to date
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure installed packages up-to-date
  apt: upgrade=safe

- name: Install core software
  apt:
    name: ['htop', 'screen', 'fail2ban', 'openntpd', 'aptitude']
    state: present

- name: Ensure calendar installed
  apt:
    name: ncal
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int >= 11

- name: Set defaults for OpenNTPd
  copy:
    src=openntpd_defaults
    dest=/etc/default/openntpd
    owner=root
    group=root
    mode=0644
