---

- name: Ensure directory exists
  file:
    path: "/opt/phpstorm/{{phpstorm_version}}"
    state: directory
    mode: '0755'

- name: Check if PhpStorm is already installed
  stat:
    path: '/opt/phpstorm/{{phpstorm_version}}/bin'
  register: installed_bin_dir

- name: Download PhpStorm
  get_url:
    url: "https://download.jetbrains.com/webide/PhpStorm-{{phpstorm_version}}.tar.gz"
    dest: '/tmp/phpstorm-{{phpstorm_version}}.tar.gz'
  when: not installed_bin_dir.stat.exists
  register: download_result

- name: Install PhpStorm
  unarchive:
    src: '/tmp/phpstorm-{{phpstorm_version}}.tar.gz'
    dest: "/opt/phpstorm/{{phpstorm_version}}"
    extra_opts: '--strip-components=1'
  when:
    - download_result is not skipped
    - download_result.state == 'file'

- name: Add desktop entry
  template:
    src: phpstorm.desktop.j2
    dest: "/usr/share/applications/phpstorm.desktop"
