---

- name: Ensure media group is present
  group: name=media state=present

- name: Ensure users are in media group
  user: name={{ item }} groups=media append=yes
  with_items: "{{ media_users }}"

- name: create directories
  file:
    path: "{{ media_root_dir }}"
    owner: nobody
    group: media
    mode: "0775"
    state: directory
