---

- name: Enable jessie backports
  apt_repository:
    repo='deb http://ftp.debian.org/debian jessie-backports main'
    state=present
    update_cache=yes

- name: Install ffmpeg from backports
  apt:
    default_release='jessie-backports'
    name='ffmpeg'
    state=present
