---

- include: ffmpeg-backports.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int < 9

- name: Ensure that gip dependencies are installed
  apt:
    name:
      - perl
      - ffmpeg
      - atomicparsley
      - ffmpeg2theora
      - libwww-perl
      - libxml-simple-perl
      - libmojolicious-perl
      - git
      - xsltproc
      - postfix
    state: present
