---

- include: ffmpeg-backports.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int < 9

- name: Ensure that gip dependencies are installed
  apt: name={{ item }} state=present
  with_items:
    - perl
    - ffmpeg
    - atomicparsley
    - ffmpeg2theora
    - libav-tools
    - libwww-perl
    - libxml-simple-perl
    - libmojolicious-perl
    - git

- name: Ensure that gip is latest version
  git:
    dest=/usr/local/src/get_iplayer
    repo='https://github.com/get-iplayer/get_iplayer.git'

- name: Set up symlink
  file:
    force=yes
    group=staff
    owner=root
    path=/usr/local/bin/get_iplayer
    src=/usr/local/src/get_iplayer/get_iplayer
    state=link

- name: Set up lockfile
  file:
    group=media
    owner=root
    mode=0775
    path=/var/shutdown_block
    state=directory

- name: Set up run script
  template:
    dest=/usr/local/bin/get_iplayer_run
    group=staff
    owner=root
    mode=0775
    src=get_iplayer.sh.j2

- name: Set up weekday cron job
  cron:
    cron_file=get-iplayer
    name=weekdays
    user=dezza
    minute=*/15
    hour=2-4
    dow=1-5
    state=present
    job=/usr/local/bin/get_iplayer_run

- name: Set up weekday cron job
  cron:
    cron_file=get-iplayer
    name=weekends
    user=dezza
    minute=*/15
    hour=2-18
    dow=6,7
    state=present
    job=/usr/local/bin/get_iplayer_run
