---

- import_tasks: installation-bullseye.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int <= 11

- import_tasks: installation-bookworm.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int >= 12

- import_tasks: installation-common.yml
