---

- include: installation-bullseye.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int <= 11

- include: installation-bookworm.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version|int >= 12

- include: installation-common.yml
