---
- name: Ensure transmission is installed
  apt:
    name: ['transmission-daemon', 'transmission-cli']
    state: present
  notify: restart transmission

- name: Ensure transmission config is correct
  template:
    src=settings.json.j2
    dest=/etc/transmission-daemon/settings.json
    owner=debian-transmission
    group=debian-transmission
    mode=0600
  notify: reload transmission

- name: Ensure transmission deamon set to use correct config
  lineinfile:
    dest: /lib/systemd/system/transmission-daemon.service
    regexp: ^ExecStart
    line: "ExecStart=/usr/bin/transmission-daemon -f --log-error -g /etc/transmission-daemon"
  notify:
    - restart transmission

- name: Ensure transmission client user is set up
  user:
    name: "{{ transmission.client_user }}"
    state: present
    create_home: true
    system: true

- name: Set up authorized keys for transmission client
  ansible.posix.authorized_key:
    user: "{{ transmission.client_user }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ transmission.client_keys }}"
