---
- name: Ensure media software is installed
  apt:
   name={{ item }} state=present
  with_items:
    - cifs-utils
    - smbclient
    - vlc
    - puddletag
    - sshfs

- name: Ensure sbmpasswords file is set
  template:
    src=smbpasswds.j2
    dest=/etc/smbpasswds
    owner=root
    group=root
    mode=0600

- name: Ensure that fstab has correct line
  lineinfile:
   dest=/etc/fstab
   line='//henrietta.internal.dezzanet.co.uk/media /media/media_hen/ cifs credentials=/etc/smbpasswds,dir_mode=0777,file_mode=0777 0 0'
