---
galaxy_info:
  role_name: redshift
  author: Derek Kaye
  description: Allows redshift to be installed
  license: GPLv3
  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye

dependencies: []
