---

- name: Ensure keyrings directory is present
  file:
    path=/etc/apt/keyrings
    state=directory

- name: Check if key is present
  stat:
    path: '/etc/apt/keyrings/slacktechnologies_slack-archive-keyring.gpg'
  register: apt_key_installed

- name: Download signing key
  get_url:
    url: "https://packagecloud.io/slacktechnologies/slack/gpgkey"
    dest: '/tmp/slack.asc'
  when: not apt_key_installed.stat.exists
  register: download_result

- name: Dearmour key
  ansible.builtin.shell: gpg --dearmor -o /etc/apt/keyrings/slacktechnologies_slack-archive-keyring.gpg /tmp/slack.asc
  when:
    - download_result is not skipped
    - download_result.state is defined
    - download_result.state == 'file'

- name: Ensure proxy is avoided
  copy:
    src=apt-config
    dest=/etc/apt/apt.conf.d/40slack
    owner=root
    group=root
    mode=0644

- name: Ensure apt source is configured
  apt_repository:
    filename: slacktechnologies_slack
    repo: deb [signed-by=/etc/apt/keyrings/slacktechnologies_slack-archive-keyring.gpg] https://packagecloud.io/slacktechnologies/slack/debian/ jessie main

- name: Install slack
  package:
    name:  slack-desktop
    state: present
