---
galaxy_info:
  role_name: intellij
  author: Derek Kaye
  description: Installs tools for Open Street Map editing
  license: GPLv3
  min_ansible_version: 2.14

  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies: []
