---

- name: "Ensure backup root dir present"
  file:
     path="{{ backup_base_dir }}"
     state=directory
     owner=root
     group=media
     mode=0755

- name: "Ensure backup destination dirs present"
  file:
    path="{{ backup_base_dir }}/{{ item.dirname }}"
    state=directory
    owner="{{ item.owner }}"
    group="{{ item.owner }}"
    mode=0750
  with_items: "{{ backup_dirs }}"
