---

- name: Ensure that printer admins are configured
  user: name={{ item }} groups=lpadmin append=yes
  with_items:
    "{{ printer_admins }}"

- name: Ensure that cups is installed
  apt:
    name: ['cups', 'cups-client', 'printer-driver-gutenprint']
    state: present
  notify:
    - restart cups

- name: Ensure that cups config is correct
  template: dest=/etc/cups/cupsd.conf backup=yes src=cupsd.conf.j2
  notify:
    - restart cups

