---

- name: Ensure dependencies are installed
  apt:
    name:
      - perl
      - git
      - cpanminus
      - postfix
    state: present

- name: Ensure cpan dependencies are installed
  cpanm: name={{ item }}
  with_items:
    - Module::Install
    - Config::Tiny
    - Transmission::Client

- name: Ensure tvmanagement is checked out
  git:
    dest={{ tv_management.install_dir }}
    repo='https://github.com/dezzak/tv-management.git'

- name: Ensure config present
  template:
    src=tv-management.ini.j2
    dest=/home/{{ tv_management_user }}/.tv-management.ini
    group={{ tv_management_group }}
    owner={{ tv_management_user }}
    mode=0600

- name: Ensure torrent monitor script set up
  cron:
    cron_file=tv-management
    user={{ tv_management_user }}
    minute=*/6
    state=present
    job="{{ tv_management.install_dir }}/torrent_monitor.pl"
    name="torrent monitor"

- name: Ensure iplayer renamer script set up
  cron:
    cron_file=tv-management
    user={{ tv_management_user }}
    minute=*/5
    state=present
    job="{{ tv_management.install_dir }}/iplayer_renamer.pl"
    name="iplayer renamer"

- name: Ensure management user in transmission group
  user:
    append: true
    groups:
      - "{{ transmission_group }}"
    name: "{{ tv_management_user }}"
