---

- name: Ensure directory exists
  file:
    path: "/opt/clion/{{clion_version}}"
    state: directory
    mode: '0755'

- name: Check if CLion is already installed
  stat:
    path: '/opt/clion/{{clion_version}}/bin'
  register: installed_bin_dir

- name: Download CLion
  get_url:
    url: "https://download-cdn.jetbrains.com/cpp/CLion-{{clion_version}}.tar.gz"
    dest: '/tmp/clion-{{clion_version}}.tar.gz'
  when: not installed_bin_dir.stat.exists
  register: download_result

- name: Install PyCharm
  unarchive:
    src: '/tmp/clion-{{clion_version}}.tar.gz'
    dest: "/opt/clion/{{clion_version}}"
    extra_opts: '--strip-components=1'
  when:
    - download_result is not skipped
    - download_result.state is defined
    - download_result.state == 'file'

- name: Add desktop entry
  template:
    src: clion.desktop.j2
    dest: "/usr/share/applications/clion.desktop"
