---

- name: Ensure that apcupsd is installed
  apt: name="apcupsd" state=present
  notify: restart apcupsd

- name: Ensure that apcupsd is configured
  template:
    src=apcupsd.conf.j2
    dest=/etc/apcupsd/apcupsd.conf
    owner=root
    group=root
    mode=0640
  notify: restart apcupsd

- name: Ensure that apcupsd is enabled
  lineinfile:
    dest=/etc/default/apcupsd
    regexp=^ISCONFIGURED=
    line='ISCONFIGURED=yes'
  notify: restart apcupsd
