---
galaxy_info:
  role_name: intellij
  author: Derek Kaye
  description: Allows IntelliJ IDEA to be installed
  license: GPLv3
  min_ansible_version: 2.7

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye

dependencies: []
